### ISSUE TITLE
[PE-D][Tester D] The last person card is partially hidden

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-2/tp#119]
![Screenshot 2022-10-28 at 4.21.20 PM.png](https://raw.githubusercontent.com/asaierika/ped/main/files/61e0b92d-2ba5-4048-a35f-a4e9fd4c34b6.png)

The last person card is not fully shown even when the scroll bar has reached the bottom. The person card is shown fully only after manually resizing the window.

![Screenshot 2022-10-28 at 4.21.52 PM.png](https://raw.githubusercontent.com/asaierika/ped/main/files/1f667290-36d2-4259-9715-8c3b8854e4f2.png)

You may want to check if it is due to the settings of the max_height of the VBox.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: asaierika/ped#2

**Comment by gabyang** [comment]
unable to replicate this bug on our devices
