### ISSUE TITLE
[PE-D][Tester D] Unable to find person by birthday

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-2/tp#127]
![Screenshot 2022-10-28 at 4.30.36 PM.png](https://raw.githubusercontent.com/asaierika/ped/main/files/d8f4353f-f1cb-45d6-95b4-ca74726ddfeb.png)

Unable to find person by birthday as instructed on User Guide. However, I was able to execute the `find` command with the name and birthday fields both present. But the result ignores the birthday field and returns the person even if the birthday does not match.

![Screenshot 2022-10-28 at 4.32.53 PM.png](https://raw.githubusercontent.com/asaierika/ped/main/files/db34bec2-b081-4d4b-b827-035bc097bf87.png)

![Screenshot 2022-10-28 at 4.33.18 PM.png](https://raw.githubusercontent.com/asaierika/ped/main/files/e7718d94-b3b4-40b4-8b9b-7b619302dbbc.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: asaierika/ped#3

**Comment by edricyeo** [comment]
Closed with #166
