### ISSUE TITLE
[PE-D][Tester C] Finding using birthday tag does not seem to work.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-2/tp#139]
![Screenshot 2022-10-28 at 4.48.34 PM.png](https://raw.githubusercontent.com/angkl0/ped/main/files/a44013ed-0ac9-4493-8013-36bdafb7105f.png)
In the above screenshot, there is a valid match but an invalid command format is returned. Furthermore, it is mentioned in the user guide that all prefixes are optional.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: angkl0/ped#6

**Comment by edricyeo** [comment]
Closed with #166
